package main

import (
	"encoding/json"
	"fmt"
	"html"
	"sort"
	"strings"
	"time"
)

func computeScore(r *Report) {
	r.Counts = map[string]int{"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
	score := 100
	for _, f := range r.Findings {
		r.Counts[f.Severity.String()]++
		switch f.Severity {
		case CRITICAL:
			score -= 20
		case HIGH:
			score -= 10
		case MEDIUM:
			score -= 4
		case LOW:
			score -= 1
		}
	}
	if score < 0 {
		score = 0
	}
	r.Score = score
	// stable sort: severity desc, then category
	sort.SliceStable(r.Findings, func(i, j int) bool {
		if r.Findings[i].Severity != r.Findings[j].Severity {
			return r.Findings[i].Severity > r.Findings[j].Severity
		}
		return r.Findings[i].Category < r.Findings[j].Category
	})
	sort.Strings(r.Emails)
}

// ---- text ----

func colorFor(s Severity) string {
	switch s {
	case CRITICAL:
		return "\033[1;91m"
	case HIGH:
		return "\033[91m"
	case MEDIUM:
		return "\033[93m"
	case LOW:
		return "\033[96m"
	default:
		return "\033[90m"
	}
}

func renderText(r *Report, color bool) string {
	c := func(code, s string) string {
		if !color {
			return s
		}
		return code + s + "\033[0m"
	}
	var b strings.Builder
	b.WriteString("\n")
	b.WriteString(c("\033[1;38;5;215m", "  exposure-check") + c("\033[90m", "  find what attackers can see before they do") + "\n")
	b.WriteString(fmt.Sprintf("  target: %s  ·  scope: %s  ·  repos: %d\n", r.Target, r.Scope, r.ReposSeen))
	b.WriteString("  " + strings.Repeat("─", 60) + "\n")
	sc := fmt.Sprintf("%d/100", r.Score)
	scColor := "\033[91m"
	if r.Score >= 80 {
		scColor = "\033[92m"
	} else if r.Score >= 50 {
		scColor = "\033[93m"
	}
	b.WriteString("  Posture score: " + c(scColor+"\033[1m", sc) + "\n")
	b.WriteString(fmt.Sprintf("  %s  %s  %s  %s\n",
		c(colorFor(CRITICAL), fmt.Sprintf("CRITICAL %d", r.Counts["CRITICAL"])),
		c(colorFor(HIGH), fmt.Sprintf("HIGH %d", r.Counts["HIGH"])),
		c(colorFor(MEDIUM), fmt.Sprintf("MEDIUM %d", r.Counts["MEDIUM"])),
		c(colorFor(LOW), fmt.Sprintf("LOW %d", r.Counts["LOW"]))))
	b.WriteString("  " + strings.Repeat("─", 60) + "\n\n")
	if len(r.Findings) == 0 {
		b.WriteString(c("\033[92m", "  No exposure findings. ") + "Keep it that way.\n\n")
	}
	for _, f := range r.Findings {
		b.WriteString("  " + c(colorFor(f.Severity)+"\033[1m", "["+f.Severity.String()+"]") + " " + f.Title + "\n")
		if f.Location != "" {
			b.WriteString(c("\033[90m", "        ↳ "+f.Location) + "\n")
		}
		if f.Detail != "" {
			b.WriteString(c("\033[37m", "        "+f.Detail) + "\n")
		}
		if f.Remedy != "" {
			b.WriteString(c("\033[90m", "        fix: "+f.Remedy) + "\n")
		}
		b.WriteString("\n")
	}
	if len(r.Emails) > 0 {
		b.WriteString(c("\033[1m", "  Corporate emails in public commit metadata:") + "\n")
		for _, e := range r.Emails {
			b.WriteString("        " + e + "\n")
		}
		b.WriteString("\n")
	}
	return b.String()
}

// ---- json ----

func renderJSON(r *Report) string {
	b, _ := json.MarshalIndent(r, "", "  ")
	return string(b)
}

// ---- markdown ----

func renderMarkdown(r *Report) string {
	var b strings.Builder
	b.WriteString("# exposure-check report\n\n")
	b.WriteString(fmt.Sprintf("**Target:** `%s` · **Scope:** %s · **Repositories scanned:** %d · %s\n\n", r.Target, r.Scope, r.ReposSeen, r.Generated.Format(time.RFC1123)))
	b.WriteString(fmt.Sprintf("**Posture score: %d/100**\n\n", r.Score))
	b.WriteString(fmt.Sprintf("| CRITICAL | HIGH | MEDIUM | LOW |\n|:--:|:--:|:--:|:--:|\n| %d | %d | %d | %d |\n\n",
		r.Counts["CRITICAL"], r.Counts["HIGH"], r.Counts["MEDIUM"], r.Counts["LOW"]))
	if len(r.Findings) == 0 {
		b.WriteString("_No exposure findings._\n")
	} else {
		b.WriteString("## Findings\n\n| Severity | Finding | Location |\n|:--|:--|:--|\n")
		for _, f := range r.Findings {
			loc := f.Location
			if loc == "" {
				loc = "—"
			}
			b.WriteString(fmt.Sprintf("| **%s** | %s | `%s` |\n", f.Severity.String(), f.Title, loc))
		}
	}
	if len(r.Emails) > 0 {
		b.WriteString("\n## Exposed emails\n\n")
		for _, e := range r.Emails {
			b.WriteString("- `" + e + "`\n")
		}
	}
	b.WriteString("\n---\n_Generated by [exposure-check](https://github.com/bariskececi/exposure-check) — educational & defensive use only._\n")
	return b.String()
}

// ---- sarif (GitHub Code Scanning) ----

type sarifSchema struct {
	Schema  string     `json:"$schema"`
	Version string     `json:"version"`
	Runs    []sarifRun `json:"runs"`
}
type sarifRun struct {
	Tool    sarifTool     `json:"tool"`
	Results []sarifResult `json:"results"`
}
type sarifTool struct {
	Driver sarifDriver `json:"driver"`
}
type sarifDriver struct {
	Name    string      `json:"name"`
	Version string      `json:"version"`
	InfoURI string      `json:"informationUri"`
	Rules   []sarifRule `json:"rules"`
}
type sarifRule struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	ShortDesc   sarifMessage     `json:"shortDescription"`
	DefaultConf sarifDefaultConf `json:"defaultConfiguration"`
}
type sarifDefaultConf struct {
	Level string `json:"level"`
}
type sarifResult struct {
	RuleID    string          `json:"ruleId"`
	Level     string          `json:"level"`
	Message   sarifMessage    `json:"message"`
	Locations []sarifLocation `json:"locations,omitempty"`
}
type sarifMessage struct {
	Text string `json:"text"`
}
type sarifLocation struct {
	PhysicalLocation sarifPhysical `json:"physicalLocation"`
}
type sarifPhysical struct {
	ArtifactLocation sarifArtifact `json:"artifactLocation"`
	Region           *sarifRegion  `json:"region,omitempty"`
}
type sarifArtifact struct {
	URI string `json:"uri"`
}
type sarifRegion struct {
	StartLine int `json:"startLine"`
}

func sarifLevel(s Severity) string {
	switch s {
	case CRITICAL, HIGH:
		return "error"
	case MEDIUM:
		return "warning"
	default:
		return "note"
	}
}

func renderSARIF(r *Report) string {
	ruleIndex := map[string]int{}
	var rules []sarifRule
	var results []sarifResult

	for _, f := range r.Findings {
		if _, ok := ruleIndex[f.Rule]; !ok {
			ruleIndex[f.Rule] = len(rules)
			rules = append(rules, sarifRule{
				ID:        f.Rule,
				Name:      f.Rule,
				ShortDesc: sarifMessage{Text: f.Title},
				DefaultConf: sarifDefaultConf{
					Level: sarifLevel(f.Severity),
				},
			})
		}

		msg := f.Title
		if f.Detail != "" {
			msg += " — " + f.Detail
		}
		if f.Remedy != "" {
			msg += " Fix: " + f.Remedy
		}

		res := sarifResult{
			RuleID:  f.Rule,
			Level:   sarifLevel(f.Severity),
			Message: sarifMessage{Text: msg},
		}

		if f.Location != "" {
			uri := f.Location
			line := 1
			if idx := strings.LastIndex(uri, ":"); idx > 0 {
				if n, err := fmt.Sscanf(uri[idx+1:], "%d", &line); n == 1 && err == nil {
					uri = uri[:idx]
				}
			}
			res.Locations = []sarifLocation{{
				PhysicalLocation: sarifPhysical{
					ArtifactLocation: sarifArtifact{URI: uri},
					Region:           &sarifRegion{StartLine: line},
				},
			}}
		}

		results = append(results, res)
	}

	s := sarifSchema{
		Schema:  "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json",
		Version: "2.1.0",
		Runs: []sarifRun{{
			Tool: sarifTool{
				Driver: sarifDriver{
					Name:    "exposure-check",
					Version: r.Version,
					InfoURI: "https://github.com/bariskececi/exposure-check",
					Rules:   rules,
				},
			},
			Results: results,
		}},
	}
	b, _ := json.MarshalIndent(s, "", "  ")
	return string(b)
}

// ---- html (the shareable report) ----

func renderHTML(r *Report) string {
	esc := html.EscapeString
	sevColor := map[string]string{"CRITICAL": "#e0512f", "HIGH": "#ef8f4a", "MEDIUM": "#e6b455", "LOW": "#8ba4a8", "INFO": "#565b55"}
	scoreColor := "#e0512f"
	if r.Score >= 80 {
		scoreColor = "#6fae5a"
	} else if r.Score >= 50 {
		scoreColor = "#f2a24a"
	}
	var find strings.Builder
	if len(r.Findings) == 0 {
		find.WriteString(`<div class="empty">No exposure findings. Nicely locked down.</div>`)
	}
	for _, f := range r.Findings {
		col := sevColor[f.Severity.String()]
		find.WriteString(`<div class="f"><div class="fh"><span class="sev" style="color:` + col + `;border-color:` + col + `">` + f.Severity.String() + `</span><span class="ft">` + esc(f.Title) + `</span><span class="cat">` + esc(f.Category) + `</span></div>`)
		if f.Location != "" {
			find.WriteString(`<div class="loc">` + esc(f.Location) + `</div>`)
		}
		if f.Detail != "" {
			find.WriteString(`<div class="det">` + esc(f.Detail) + `</div>`)
		}
		if f.Remedy != "" {
			find.WriteString(`<div class="fix">▸ ` + esc(f.Remedy) + `</div>`)
		}
		find.WriteString(`</div>`)
	}
	var emails strings.Builder
	for _, e := range r.Emails {
		emails.WriteString(`<span class="em">` + esc(e) + `</span>`)
	}
	tile := func(label, val, col string) string {
		return `<div class="tile"><div class="tv" style="color:` + col + `">` + val + `</div><div class="tl">` + label + `</div></div>`
	}
	return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>exposure-check report — ` + esc(r.Target) + `</title>
<link href="https://fonts.googleapis.com/css2?family=Saira+Condensed:wght@600;700&family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500&display=swap" rel="stylesheet">
<style>
:root{--bg:#0d1113;--panel:#12181a;--hair:#26302f;--hair2:#19201f;--ink:#ddd6c6;--dim:#8b877a;--faint:#565b55;--sodium:#f2a24a;--mono:'IBM Plex Mono',monospace;--disp:'Saira Condensed',sans-serif;--sans:'IBM Plex Sans',sans-serif}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);
background-image:linear-gradient(rgba(139,164,168,.03) 1px,transparent 1px),linear-gradient(90deg,rgba(139,164,168,.03) 1px,transparent 1px);background-size:32px 32px}
.wrap{max-width:900px;margin:0 auto;padding:40px 24px 60px}
.kick{font-family:var(--mono);font-size:11px;letter-spacing:3px;text-transform:uppercase;color:var(--sodium);display:flex;gap:9px;align-items:center}
.kick::before{content:"";width:16px;height:2px;background:var(--sodium)}
h1{font-family:var(--disp);font-weight:700;font-size:44px;letter-spacing:-.5px;margin:10px 0 2px}
.meta{font-family:var(--mono);font-size:12px;color:var(--dim)}
.score{display:flex;align-items:center;gap:26px;margin:28px 0;padding:22px;background:var(--panel);border:1px solid var(--hair)}
.scoreN{font-family:var(--disp);font-weight:700;font-size:72px;line-height:.8}
.scoreL{font-family:var(--mono);font-size:11px;letter-spacing:2px;text-transform:uppercase;color:var(--dim)}
.tiles{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--hair);border:1px solid var(--hair);flex:1}
.tile{background:var(--panel);padding:12px 14px}.tv{font-family:var(--disp);font-weight:700;font-size:26px;line-height:1}.tl{font-family:var(--mono);font-size:9px;letter-spacing:1px;text-transform:uppercase;color:var(--dim);margin-top:4px}
.sh{font-family:var(--mono);font-size:11px;letter-spacing:2px;text-transform:uppercase;color:var(--faint);margin:30px 0 12px;border-bottom:1px solid var(--hair);padding-bottom:8px}
.f{background:var(--panel);border:1px solid var(--hair);border-left:3px solid var(--hair);padding:14px 16px;margin-bottom:10px}
.fh{display:flex;align-items:center;gap:12px;flex-wrap:wrap}
.sev{font-family:var(--disp);font-weight:700;font-size:11px;letter-spacing:1px;border:1px solid;padding:2px 8px}
.ft{font-family:var(--disp);font-weight:600;font-size:18px;color:#fff}
.cat{font-family:var(--mono);font-size:9px;letter-spacing:1px;text-transform:uppercase;color:var(--faint);margin-left:auto}
.loc{font-family:var(--mono);font-size:11px;color:var(--sodium);margin-top:8px;word-break:break-all}
.det{font-size:13px;color:var(--dim);line-height:1.55;margin-top:6px}
.fix{font-family:var(--mono);font-size:11.5px;color:var(--ink);line-height:1.55;margin-top:8px}
.empty{padding:20px;background:var(--panel);border:1px solid var(--hair);color:#6fae5a;font-family:var(--mono)}
.ems{display:flex;flex-wrap:wrap;gap:8px}.em{font-family:var(--mono);font-size:12px;color:var(--ink);background:var(--panel);border:1px solid var(--hair2);padding:5px 10px}
footer{margin-top:34px;font-family:var(--mono);font-size:11px;color:var(--faint);line-height:1.6;border-top:1px solid var(--hair);padding-top:16px}
footer a{color:var(--sodium)}
@media(max-width:640px){.score{flex-direction:column;align-items:flex-start}.tiles{width:100%}}
</style></head><body><div class="wrap">
<div class="kick">exposure-check · attack-surface report</div>
<h1>` + esc(r.Target) + `</h1>
<div class="meta">scope: ` + esc(r.Scope) + ` · repositories scanned: ` + itoa(r.ReposSeen) + ` · ` + r.Generated.Format("2006-01-02 15:04 MST") + `</div>
<div class="score"><div><div class="scoreN" style="color:` + scoreColor + `">` + itoa(r.Score) + `</div><div class="scoreL">posture score / 100</div></div>
<div class="tiles">` +
		tile("Critical", itoa(r.Counts["CRITICAL"]), sevColor["CRITICAL"]) +
		tile("High", itoa(r.Counts["HIGH"]), sevColor["HIGH"]) +
		tile("Medium", itoa(r.Counts["MEDIUM"]), sevColor["MEDIUM"]) +
		tile("Emails", itoa(len(r.Emails)), "#8ba4a8") +
		`</div></div>
<div class="sh">Findings</div>` + find.String() +
		func() string {
			if len(r.Emails) == 0 {
				return ""
			}
			return `<div class="sh">Exposed corporate emails (public commit metadata)</div><div class="ems">` + emails.String() + `</div>`
		}() +
		`<footer>Generated by <a href="https://github.com/bariskececi/exposure-check">exposure-check</a> — an open-source exposure scanner. Educational &amp; defensive use only: scan assets you own or are authorised to assess. Secret values are redacted; rotate anything flagged.</footer>
</div></body></html>`
}
